language: node_js
branches:
  only:
    - develop
    - /^feature\//
node_js:
  - "0.12.0"
before_install:
  - npm install -g bower grunt grunt-cli istanbul jasmine-node coveralls karma karma-cli
script:
  - npm test --verbose
after_success:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage

